version: '2.4'

services:

  ubuntu-14.04:
    build:
      context: .
      dockerfile: ubuntu.dockerfile
      args:
        - OS_DIST=ubuntu
        - OS_TAG=14.04
    image: gnucashbuild:ubuntu-14.04
    container_name: gnucashbuild-ubuntu-14.04
    network_mode: host # using host network to ease XWindows connectivity
    init: true # compose file version 2.2-2.4 or 3.7+ needed for this
    tty: true
    stdin_open: true
    environment:
      - PLATFORM_CMAKE_OPTS=-DCMAKE_INSTALL_PREFIX=/opt
      - GNC_GIT_CHECKOUT=3.5
      #- BUILDTYPE=stop
      #- DISPLAY=192.168.2.23:0.0
    #volumes:
    #  - ./gnucash:/gnucash
    #  - ./build:/build

  ubuntu-16.04:
    build:
      context: .
      dockerfile: ubuntu.dockerfile
      args:
        - OS_DIST=ubuntu
        - OS_TAG=16.04
    image: gnucashbuild:ubuntu-16.04
    container_name: gnucashbuild-ubuntu-16.04
    network_mode: host # using host network to ease XWindows connectivity
    init: true # compose file version 2.2-2.4 or 3.7+ needed
    tty: true
    stdin_open: true
    environment:
      - PLATFORM_CMAKE_OPTS=-DCMAKE_INSTALL_PREFIX=/opt
      - GNC_GIT_CHECKOUT=3.5
      #- BUILDTYPE=stop
      #- DISPLAY=192.168.2.23:0.0
    #volumes:
    #  - ./gnucash:/gnucash
    #  - ./build:/build

  ubuntu-18.04:
    build:
      context: .
      dockerfile: ubuntu.dockerfile
      args:
        - OS_DIST=ubuntu
        - OS_TAG=18.04
    image: gnucashbuild:ubuntu-18.04
    container_name: gnucashbuild-ubuntu-18.04
    network_mode: host # using host network to ease XWindows connectivity
    init: true # compose file version 2.2-2.4 or 3.7+ needed
    tty: true
    stdin_open: true
    environment:
      - PLATFORM_CMAKE_OPTS=-DCMAKE_INSTALL_PREFIX=/opt
      - GNC_GIT_CHECKOUT=3.5
      #- BUILDTYPE=stop
      #- DISPLAY=192.168.2.23:0.0
    #volumes:
    #  - ./gnucash:/gnucash
    #  - ./build:/build

  debian-8:
    build:
      context: .
      dockerfile: ubuntu.dockerfile
      args:
        - OS_DIST=debian
        - OS_TAG=8
    image: gnucashbuild:debian-8
    container_name: gnucashbuild-debian-8
    network_mode: host # using host network to ease XWindows connectivity
    init: true # compose file version 2.2-2.4 or 3.7+ needed
    tty: true
    stdin_open: true
    environment:
      - PLATFORM_CMAKE_OPTS=-DCMAKE_INSTALL_PREFIX=/opt
      - GNC_GIT_CHECKOUT=3.5
      #- BUILDTYPE=stop
      #- DISPLAY=192.168.2.23:0.0
    #volumes:
    #  - ./gnucash:/gnucash
    #  - ./build:/build
